[tool.poetry]
name = "diutil"
version = "0.1.0"
description = "basic util 4 my cases"
authors = ["adib-enc <adib35785@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
